---
title: "mlr3learners.lgbpy: Hyperparameter Tuning Example"
date: "`r Sys.Date()`"
output:
  rmarkdown::html_vignette:
    keep_md: true
vignette: >
  %\VignetteIndexEntry{mlr3learners_lightgbm_tuning}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  eval = FALSE
)
```

```{r setup}
library(mlr3)
library(mlr3learners.lightgbm)
library(paradox)
```

# Load the dataset 

```{r}
task <- mlr3::tsk("pima")
```

```{r}
set.seed(17)
split <- list(
  train_index = sample(seq_len(task$nrow), size = 0.7 * task$nrow)
)
temp_split <- setdiff(seq_len(task$nrow), split$train_index)
set.seed(17)
split$valid_index <- sample(temp_split, size = 0.5 * length(temp_split))
split$test_index <- setdiff(temp_split, split$valid_index)
```

# Instantiate the lightgbm learner 

Initially, the `classif.lgbpy` class needs to be instantiated: 

```{r}
learner <- mlr3::lrn("classif.lightgbm")
```

# Configure the learner 

```{r}
learner$early_stopping_rounds <- 100
learner$nrounds <- 1000
```

```{r}
learner$param_set$values <- list(
  "objective" = "binary",
  "learning_rate" = 0.1,
  "seed" = 17L,
  "bagging_freq" = 5L,
  "num_threads" = 1L,
  "metric" = "auc"
)

tune_ps <- ParamSet$new(list(
  ParamDbl$new("bagging_fraction", lower = 0.4, upper = 1),
  ParamInt$new("min_data_in_leaf", lower = 5, upper = 30)
))
```

# Resampling strategy

```{r}
resamp <- mlr3::rsmp("cv", folds = 5)
measure <- mlr3::msr("classif.auc")
```

# Train the learner 

```{r}
terminate <- mlr3tuning::term("stagnation", iters = 10, threshold = 0)

instance <- mlr3tuning::TuningInstance$new(
  task = task,
  learner = learner,
  resampling = resamp,
  measures = measure,
  param_set = tune_ps,
  terminator = terminate
)
instance
```

```{r}
future::plan("multisession")
tuner <- mlr3tuning::tnr("grid_search", resolution = 5)
set.seed(17)
result <- tuner$tune(instance)
future::plan("sequential")
```

```{r}
best <- instance$best()
best$score(mlr3::msr("classif.auc"))
```

```{r}
instance$archive(unnest = "params")[, c("bagging_fraction", "min_data_in_leaf", "classif.auc")]
```

```{r}
instance$result$params
learner$param_set$values <- instance$result$params
learner$train(task, row_ids = split$train_index)
```

```{r}
learner$model$current_iter()
```

```{r}
predictions <- learner$predict(task, row_ids = split$test_index)
head(predictions$response)
```

```{r}
predictions$confusion
```

```{r}
predictions$score(mlr3::msr("classif.logloss"))
predictions$score(mlr3::msr("classif.auc"))
```

```{r}
importance <- learner$importance()
importance
```
